name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: "npm"
          node-version-file: ".node_version"
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check
        run: |
          npx @inlang/paraglide-js compile --project ./project.inlang --outdir ./src/lib/paraglide
          npm run check
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".node_version"
          cache: "npm"
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: npm run build
  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".node_version"
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Run Vitest Tests
        run: npm run test:unit
  test-e2e:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: true
      matrix:
        project:
          [
            { name: chrome-mobile, browser: chromium },
            { name: safari-mobile, browser: webkit },
          ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".node_version"
          cache: "npm"
      - name: Install npm Dependencies
        run: npm ci
      - name: Install Browser Dependencies
        run: npx playwright install ${{ matrix.project.browser }} --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.project.name }}
      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.project.name }}
          path: blob-report
          retention-days: 1
  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [test-e2e]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".node_version"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v5
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge into JSON Report
        run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright merge-reports --reporter json ./all-blob-reports
      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: results.json
